"""Add PostgreSQL indexes and cascade deletes

Revision ID: 2c86936a13ce
Revises: c6d69dae716b
Create Date: 2025-12-23 15:36:18.222178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c86936a13ce'
down_revision = 'c6d69dae716b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_payments_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_payments_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_id'), ['transaction_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('payments_challenge_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payments_subscription_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payments_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user_challenges', ['challenge_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('idx_trades_challenge_status', ['challenge_id', 'status'], unique=False)
        batch_op.create_index('idx_trades_opened_at', ['opened_at'], unique=False)
        batch_op.create_index('idx_trades_symbol', ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)
        batch_op.drop_constraint(batch_op.f('trades_challenge_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_challenges', ['challenge_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.create_index('idx_challenges_phase', ['phase'], unique=False)
        batch_op.create_index('idx_challenges_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_challenges_user_status', ['user_id', 'status'], unique=False)
        batch_op.drop_constraint(batch_op.f('user_challenges_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_referral_code_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_users_role', ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_referred_by_code'), ['referred_by_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_referred_by_code'))
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_role')
        batch_op.drop_index('idx_users_created_at')
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_referral_code_key'), ['referral_code'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_challenges_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index('idx_challenges_user_status')
        batch_op.drop_index('idx_challenges_start_date')
        batch_op.drop_index('idx_challenges_phase')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trades_challenge_id_fkey'), 'user_challenges', ['challenge_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index('idx_trades_symbol')
        batch_op.drop_index('idx_trades_opened_at')
        batch_op.drop_index('idx_trades_challenge_status')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payments_subscription_id_fkey'), 'subscriptions', ['subscription_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payments_challenge_id_fkey'), 'user_challenges', ['challenge_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_payments_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index('idx_payments_user_status')
        batch_op.drop_index('idx_payments_created_at')

    # ### end Alembic commands ###
