"""Add cascade deletes to all foreign keys

Revision ID: bc3f08f61bd8
Revises: 2c86936a13ce
Create Date: 2025-12-23 15:43:30.228363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3f08f61bd8'
down_revision = '2c86936a13ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_usages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('offer_usages_offer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('offer_usages_payment_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('offer_usages_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'offers', ['offer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'payments', ['payment_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index('idx_payouts_user_status', ['user_id', 'status'], unique=False)
        batch_op.drop_constraint(batch_op.f('payouts_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payouts_challenge_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user_challenges', ['challenge_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('points_balances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('points_balances_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('points_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_points_tx_type', ['transaction_type'], unique=False)
        batch_op.create_index('idx_points_tx_user', ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('points_transactions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index('idx_referrals_referrer', ['referrer_id'], unique=False)
        batch_op.create_index('idx_referrals_status', ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('referrals_referred_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('referrals_referrer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['referrer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['referred_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_subscriptions_status', ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('subscriptions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index('idx_tickets_user_status', ['user_id', 'status'], unique=False)
        batch_op.drop_constraint(batch_op.f('support_tickets_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ticket_messages_ticket_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ticket_messages_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'support_tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ticket_messages_sender_id_fkey'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ticket_messages_ticket_id_fkey'), 'support_tickets', ['ticket_id'], ['id'])

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('support_tickets_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index('idx_tickets_user_status')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscriptions_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index('idx_subscriptions_status')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('referrals_referrer_id_fkey'), 'users', ['referrer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('referrals_referred_id_fkey'), 'users', ['referred_id'], ['id'])
        batch_op.drop_index('idx_referrals_status')
        batch_op.drop_index('idx_referrals_referrer')

    with op.batch_alter_table('points_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('points_transactions_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index('idx_points_tx_user')
        batch_op.drop_index('idx_points_tx_type')

    with op.batch_alter_table('points_balances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('points_balances_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payouts_challenge_id_fkey'), 'user_challenges', ['challenge_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payouts_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index('idx_payouts_user_status')

    with op.batch_alter_table('offer_usages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('offer_usages_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('offer_usages_payment_id_fkey'), 'payments', ['payment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('offer_usages_offer_id_fkey'), 'offers', ['offer_id'], ['id'])

    # ### end Alembic commands ###
