"""Add config_type to platform_config

Revision ID: e3ae470e791a
Revises: f27547509dce
Create Date: 2025-12-25 21:15:10.696806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3ae470e791a'
down_revision = 'f27547509dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_blog_comments_approved'))
        batch_op.drop_index(batch_op.f('idx_blog_comments_post'))
        batch_op.drop_constraint(batch_op.f('blog_comments_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'])

    with op.batch_alter_table('blog_post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blog_post_likes_post_id_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_post_like', ['post_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('blog_post_likes_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'])

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_blog_posts_author'))
        batch_op.drop_index(batch_op.f('idx_blog_posts_published'))
        batch_op.drop_index(batch_op.f('idx_blog_posts_slug'))
        batch_op.drop_index(batch_op.f('idx_blog_posts_status'))

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_likes_comment_id_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_comment_like', ['comment_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('comment_likes_comment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'idea_comments', ['comment_id'], ['id'])

    with op.batch_alter_table('copied_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_copied_trades_rel'))

    with op.batch_alter_table('copy_relationships', schema=None) as batch_op:
        batch_op.alter_column('allowed_symbols',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('excluded_symbols',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('copy_relationships_copier_id_master_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_copy_rel_copier'))
        batch_op.drop_index(batch_op.f('idx_copy_rel_master'))
        batch_op.create_unique_constraint('unique_copy_relationship', ['copier_id', 'master_id'])

    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_equity_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('idx_equity_snapshots_user'))

    with op.batch_alter_table('event_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_offers_active'))
        batch_op.drop_index(batch_op.f('idx_offers_event'))
        batch_op.drop_index(batch_op.f('idx_offers_promo_code'))

    with op.batch_alter_table('event_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_redemptions_date'))
        batch_op.drop_index(batch_op.f('idx_redemptions_event'))
        batch_op.drop_index(batch_op.f('idx_redemptions_user'))

    with op.batch_alter_table('follow_suggestions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('follow_suggestions_user_id_suggested_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_suggestion', ['user_id', 'suggested_user_id'])

    with op.batch_alter_table('holiday_bonuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_holiday_dates'))

    with op.batch_alter_table('idea_bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('idea_bookmarks_idea_id_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_idea_bookmark', ['idea_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('idea_bookmarks_idea_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trading_ideas', ['idea_id'], ['id'])

    with op.batch_alter_table('idea_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_comments_idea'))
        batch_op.drop_constraint(batch_op.f('idea_comments_idea_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trading_ideas', ['idea_id'], ['id'])

    with op.batch_alter_table('idea_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('idea_likes_idea_id_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_idea_like', ['idea_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('idea_likes_idea_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trading_ideas', ['idea_id'], ['id'])

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_notification_logs_created'))
        batch_op.drop_index(batch_op.f('idx_notification_logs_status'))
        batch_op.drop_index(batch_op.f('idx_notification_logs_user'))

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_oauth_provider'))
        batch_op.drop_index(batch_op.f('idx_oauth_provider_user_id'))
        batch_op.drop_index(batch_op.f('idx_oauth_user_id'))
        batch_op.drop_constraint(batch_op.f('oauth_accounts_provider_provider_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_oauth_provider_user', ['provider', 'provider_user_id'])

    with op.batch_alter_table('platform_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('config_data', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_platform_config_config_type'), ['config_type'], unique=True)

    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_categories_category_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_categories_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'blog_categories', ['category_id'], ['id'])

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_tags_tag_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_tags_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'blog_tags', ['tag_id'], ['id'])

    with op.batch_alter_table('promotional_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_events_dates'))
        batch_op.drop_index(batch_op.f('idx_events_slug'))
        batch_op.drop_index(batch_op.f('idx_events_status'))

    with op.batch_alter_table('push_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_push_devices_user'))
        batch_op.drop_constraint(batch_op.f('push_devices_user_id_device_token_key'), type_='unique')
        batch_op.create_unique_constraint('unique_user_device', ['user_id', 'device_token'])

    with op.batch_alter_table('trader_followers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_followers_follower'))
        batch_op.drop_index(batch_op.f('idx_followers_following'))
        batch_op.drop_constraint(batch_op.f('trader_followers_follower_id_following_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_follow_relationship', ['follower_id', 'following_id'])

    with op.batch_alter_table('trader_profiles', schema=None) as batch_op:
        batch_op.alter_column('preferred_markets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('preferred_pairs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('badges',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('trader_statistics', schema=None) as batch_op:
        batch_op.alter_column('monthly_returns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('trading_ideas', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.drop_index(batch_op.f('idx_ideas_created'))
        batch_op.drop_index(batch_op.f('idx_ideas_status'))
        batch_op.drop_index(batch_op.f('idx_ideas_symbol'))
        batch_op.drop_index(batch_op.f('idx_ideas_user'))

    with op.batch_alter_table('webinar_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_webinar_questions_webinar'))

    with op.batch_alter_table('webinar_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_webinar_reg_user'))
        batch_op.drop_index(batch_op.f('idx_webinar_reg_webinar'))
        batch_op.drop_constraint(batch_op.f('webinar_registrations_webinar_id_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_webinar_registration', ['webinar_id', 'user_id'])

    with op.batch_alter_table('webinars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_webinars_scheduled_at'))
        batch_op.drop_index(batch_op.f('idx_webinars_slug'))
        batch_op.drop_index(batch_op.f('idx_webinars_status'))
        batch_op.drop_constraint(batch_op.f('webinars_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_webinars_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webinars_slug'))
        batch_op.create_unique_constraint(batch_op.f('webinars_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_webinars_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_webinars_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_webinars_scheduled_at'), ['scheduled_at'], unique=False)

    with op.batch_alter_table('webinar_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('unique_webinar_registration', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('webinar_registrations_webinar_id_user_id_key'), ['webinar_id', 'user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_webinar_reg_webinar'), ['webinar_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_webinar_reg_user'), ['user_id'], unique=False)

    with op.batch_alter_table('webinar_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_webinar_questions_webinar'), ['webinar_id'], unique=False)

    with op.batch_alter_table('trading_ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ideas_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ideas_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_ideas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_ideas_created'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('trader_statistics', schema=None) as batch_op:
        batch_op.alter_column('monthly_returns',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('trader_profiles', schema=None) as batch_op:
        batch_op.alter_column('badges',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('preferred_pairs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('preferred_markets',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('trader_followers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_follow_relationship', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('trader_followers_follower_id_following_id_key'), ['follower_id', 'following_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_followers_following'), ['following_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_followers_follower'), ['follower_id'], unique=False)

    with op.batch_alter_table('push_devices', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_device', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('push_devices_user_id_device_token_key'), ['user_id', 'device_token'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_push_devices_user'), ['user_id'], unique=False)

    with op.batch_alter_table('promotional_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_events_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_events_dates'), ['start_date', 'end_date'], unique=False)

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_tags_post_id_fkey'), 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('post_tags_tag_id_fkey'), 'blog_tags', ['tag_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_categories_post_id_fkey'), 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('post_categories_category_id_fkey'), 'blog_categories', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('platform_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_config_config_type'))
        batch_op.drop_column('config_data')
        batch_op.drop_column('config_type')

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('unique_oauth_provider_user', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('oauth_accounts_provider_provider_user_id_key'), ['provider', 'provider_user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_oauth_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_oauth_provider_user_id'), ['provider', 'provider_user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_oauth_provider'), ['provider'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_primary')

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notification_logs_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notification_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_notification_logs_created'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('idea_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('idea_likes_idea_id_fkey'), 'trading_ideas', ['idea_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_idea_like', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('idea_likes_idea_id_user_id_key'), ['idea_id', 'user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('idea_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('idea_comments_idea_id_fkey'), 'trading_ideas', ['idea_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_comments_idea'), ['idea_id'], unique=False)

    with op.batch_alter_table('idea_bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('idea_bookmarks_idea_id_fkey'), 'trading_ideas', ['idea_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_idea_bookmark', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('idea_bookmarks_idea_id_user_id_key'), ['idea_id', 'user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('holiday_bonuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_holiday_dates'), ['bonus_start', 'bonus_end'], unique=False)

    with op.batch_alter_table('follow_suggestions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_suggestion', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('follow_suggestions_user_id_suggested_user_id_key'), ['user_id', 'suggested_user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('event_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_redemptions_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_redemptions_event'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_redemptions_date'), ['redeemed_at'], unique=False)

    with op.batch_alter_table('event_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_offers_promo_code'), ['promo_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_offers_event'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_offers_active'), ['is_active'], unique=False)

    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_equity_snapshots_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_equity_snapshots_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('copy_relationships', schema=None) as batch_op:
        batch_op.drop_constraint('unique_copy_relationship', type_='unique')
        batch_op.create_index(batch_op.f('idx_copy_rel_master'), ['master_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_copy_rel_copier'), ['copier_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('copy_relationships_copier_id_master_id_key'), ['copier_id', 'master_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('excluded_symbols',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('allowed_symbols',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('copied_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_copied_trades_rel'), ['copy_relationship_id'], unique=False)

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_likes_comment_id_fkey'), 'idea_comments', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_comment_like', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('comment_likes_comment_id_user_id_key'), ['comment_id', 'user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_blog_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_blog_posts_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_blog_posts_published'), [sa.literal_column('published_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_blog_posts_author'), ['author_id'], unique=False)

    with op.batch_alter_table('blog_post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blog_post_likes_post_id_fkey'), 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_post_like', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('blog_post_likes_post_id_user_id_key'), ['post_id', 'user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blog_comments_post_id_fkey'), 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_blog_comments_post'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_blog_comments_approved'), ['is_approved'], unique=False)

    # ### end Alembic commands ###
