"""Add MT connection tables

Revision ID: f27547509dce
Revises: bc3f08f61bd8
Create Date: 2025-12-23 22:11:41.315030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f27547509dce'
down_revision = 'bc3f08f61bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_logs_action'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_action_type'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_user_id'))
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_email_queue_to_email'))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('screenshots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('journal_templates', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('kyc_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_kyc_data_status'))
        batch_op.drop_index(batch_op.f('idx_kyc_data_user_id'))

    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_kyc_documents_kyc_id'))

    with op.batch_alter_table('kyc_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_kyc_history_kyc_id'))

    with op.batch_alter_table('order_templates', schema=None) as batch_op:
        batch_op.alter_column('tp_levels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('points_redemptions', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.alter_column('favorite_symbols',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('two_factor_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_two_factor_auth_user_id'))
        batch_op.drop_constraint(batch_op.f('two_factor_auth_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_two_factor_auth_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_sessions_fingerprint'))
        batch_op.drop_index(batch_op.f('idx_user_sessions_token'))
        batch_op.drop_index(batch_op.f('idx_user_sessions_user_id'))
        batch_op.drop_constraint(batch_op.f('user_sessions_session_token_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_sessions_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_session_token'), ['session_token'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_reset_token'))
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.create_index(batch_op.f('idx_users_reset_token'), ['reset_token'], unique=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_session_token'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_device_fingerprint'))
        batch_op.create_unique_constraint(batch_op.f('user_sessions_session_token_key'), ['session_token'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_user_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_sessions_token'), ['session_token'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_sessions_fingerprint'), ['device_fingerprint'], unique=False)

    with op.batch_alter_table('two_factor_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_two_factor_auth_user_id'))
        batch_op.create_unique_constraint(batch_op.f('two_factor_auth_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_two_factor_auth_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.alter_column('favorite_symbols',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('points_redemptions', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('order_templates', schema=None) as batch_op:
        batch_op.alter_column('tp_levels',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('kyc_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_kyc_history_kyc_id'), ['kyc_id'], unique=False)

    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_kyc_documents_kyc_id'), ['kyc_id'], unique=False)

    with op.batch_alter_table('kyc_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_kyc_data_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_kyc_data_status'), ['status'], unique=False)

    with op.batch_alter_table('journal_templates', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('screenshots',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_email_queue_to_email'), ['to_email'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.create_index(batch_op.f('idx_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_action'), ['action'], unique=False)

    # ### end Alembic commands ###
